#pragma once
#include <memory>
#include <regex>
#include <vector>
#include <iostream>
#include <string>
#include <filesystem>
#include <opencv2/opencv.hpp>
#include <algorithm>
#include <utility>
#include "Log.h"
